# Games by player & season

In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../../data/nba_database")

games_path = DATA_DIR / "Games.csv"
player_stats_path = DATA_DIR / "PlayerStatistics.csv"

games = pd.read_csv(games_path) # game metadata like gameId, date, season, teams
player_stats = pd.read_csv(player_stats_path) # player-game rows, one row per player per game

print("Games:", games.shape)
print("PlayerStatistics:", player_stats.shape)

/var/folders/r2/nvsgtzs1435dg6fbzv1sn9b00000gn/T/ipykernel_2770/3930647178.py:9: DtypeWarning: Columns (12,14,18,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  games = pd.read_csv(games_path) # game metadata like gameId, date, season, teams
/var/folders/r2/nvsgtzs1435dg6fbzv1sn9b00000gn/T/ipykernel_2770/3930647178.py:10: DtypeWarning: Columns (10,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  player_stats = pd.read_csv(player_stats_path) # player-game rows, one row per player per game

Games: (73085, 22)
PlayerStatistics: (1664775, 35)

In [2]:
print(list(games.columns))
print(list(player_stats.columns))

['gameId', 'gameDateTimeEst', 'hometeamCity', 'hometeamName', 'hometeamId', 'awayteamCity', 'awayteamName', 'awayteamId', 'homeScore', 'awayScore', 'winner', 'gameType', 'gameSubtype', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'attendance', 'arenaId', 'arenaName', 'arenaCity', 'arenaState', 'officials']
['firstName', 'lastName', 'personId', 'gameId', 'gameDateTimeEst', 'playerteamCity', 'playerteamName', 'opponentteamCity', 'opponentteamName', 'gameType', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'win', 'home', 'numMinutes', 'points', 'assists', 'blocks', 'steals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersAttempted', 'threePointersMade', 'threePointersPercentage', 'freeThrowsAttempted', 'freeThrowsMade', 'freeThrowsPercentage', 'reboundsDefensive', 'reboundsOffensive', 'reboundsTotal', 'foulsPersonal', 'turnovers', 'plusMinusPoints']

In [3]:
player_stats["gameDateTimeEst"] = pd.to_datetime(
    player_stats["gameDateTimeEst"]
)

games["gameDateTimeEst"] = pd.to_datetime(
    games["gameDateTimeEst"]
)

games.head()

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,...,gameSubtype,gameLabel,gameSubLabel,seriesGameNumber,attendance,arenaId,arenaName,arenaCity,arenaState,officials
0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,1610612747,Washington,Wizards,1610612764,120,101,...,NaN,NaN,NaN,NaN,18997.0,1000069,Crypto.com Arena,Los Angeles,CA,"Sean Corbin, Josh Tiven, Pat O'Connell"
1,22501097,2026-03-30 21:30:00,Oklahoma City,Thunder,1610612760,Detroit,Pistons,1610612765,114,110,...,NaN,NaN,NaN,NaN,18203.0,1000052,Paycom Center,Oklahoma City,OK,"Scott Foster, Karl Lane, Phenizee Ransom"
2,22501096,2026-03-30 21:00:00,Utah,Jazz,1610612762,Cleveland,Cavaliers,1610612739,113,122,...,NaN,NaN,NaN,NaN,18186.0,1000106,Delta Center,Salt Lake City,UT,"JB DeRosa, David Guthrie, JD Ralls"
3,22501095,2026-03-30 20:30:00,Dallas,Mavericks,1610612742,Minnesota,Timberwolves,1610612750,94,124,...,NaN,NaN,NaN,NaN,20021.0,193,American Airlines Center,Dallas,TX,"Courtney Kirkland, Gediminas Petraitis, Robert..."
4,22501093,2026-03-30 20:00:00,Memphis,Grizzlies,1610612763,Phoenix,Suns,1610612756,105,131,...,NaN,NaN,NaN,NaN,14661.0,242,FedExForum,Memphis,TN,"James Capers, Justin Van Duyne, Brandon Schwab"

In [4]:
def get_season(date):
    year = date.year
    return year if date.month >= 9 else year - 1

player_stats["season"] = player_stats["gameDateTimeEst"].apply(get_season)

player_stats.head()

,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,opponentteamName,gameType,...,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,season
0,Luke,Kennard,1628379.0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,Washington,Wizards,Regular Season,...,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,20.0,2025.0
1,Maxi,Kleber,1628467.0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,Washington,Wizards,Regular Season,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025.0
2,Jarred,Vanderbilt,1629020.0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,Washington,Wizards,Regular Season,...,4.0,2.0,0.5,6.0,2.0,8.0,0.0,1.0,5.0,2025.0
3,Deandre,Ayton,1629028.0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,Washington,Wizards,Regular Season,...,2.0,2.0,1.0,5.0,2.0,7.0,0.0,2.0,9.0,2025.0
4,Luka,Doncic,1629029.0,22501098,2026-03-30 22:00:00,Los Angeles,Lakers,Washington,Wizards,Regular Season,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025.0

In [5]:
games_small = games[[
    "gameId",

    "homeScore",
    "awayScore",

    # "arenaName", # map chart could be added, but probably in teams dashboard
    # "arenaCity",
    # "arenaState",

    "attendance" # can be used for another stat
]]

games_small.head()

     gameId  homeScore  awayScore  attendance
0  22501098        120        101     18997.0
1  22501097        114        110     18203.0
2  22501096        113        122     18186.0
3  22501095         94        124     20021.0
4  22501093        105        131     14661.0

In [6]:
player_games = player_stats.merge(
    games_small,
    on="gameId",
    how="left"
)

player_games = player_games.drop(
    columns=["firstName", "lastName"],
    errors="ignore"
)

player_games = player_games[[
    "personId",
    "season",
    "gameId",
    "gameDateTimeEst",

    "playerteamCity",
    "playerteamName",
    "opponentteamCity",
    "opponentteamName",
    "gameType",
    "home",
    "win",

    "numMinutes",
    "points",
    "assists",
    "reboundsTotal",
    "reboundsDefensive",
    "reboundsOffensive",
    "blocks",
    "steals",
    "turnovers",
    "foulsPersonal",
    "plusMinusPoints",

    "fieldGoalsAttempted",
    "fieldGoalsMade",
    "fieldGoalsPercentage",
    "threePointersAttempted",
    "threePointersMade",
    "threePointersPercentage",
    "freeThrowsAttempted",
    "freeThrowsMade",
    "freeThrowsPercentage",

    "homeScore",
    "awayScore",
    "attendance"
]]

player_games = player_games.sort_values(
    ["personId", "season", "gameDateTimeEst"]
).reset_index(drop=True)

player_games.head()

,personId,season,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,opponentteamName,gameType,home,...,fieldGoalsPercentage,threePointersAttempted,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,homeScore,awayScore,attendance
0,2.0,1983.0,28300002,1983-10-28 20:00:00,Los Angeles,Lakers,Kansas City,Kings,Regular Season,0.0,...,0.500,0.0,0.0,0.0,0.0,0.0,0.0,107.0,117.0,NaN
1,2.0,1983.0,28300010,1983-10-29 20:00:00,Los Angeles,Lakers,Utah,Jazz,Regular Season,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,115.0,120.0,NaN
2,2.0,1983.0,28300035,1983-11-02 20:00:00,Los Angeles,Lakers,San Diego,Clippers,Regular Season,0.0,...,0.400,1.0,0.0,0.0,0.0,0.0,0.0,110.0,106.0,NaN
3,2.0,1983.0,28300053,1983-11-05 20:00:00,Los Angeles,Lakers,Dallas,Mavericks,Regular Season,0.0,...,0.213,1.0,0.0,0.0,2.0,1.0,0.5,107.0,102.0,NaN
4,2.0,1983.0,28300066,1983-11-08 20:00:00,Los Angeles,Lakers,Denver,Nuggets,Regular Season,0.0,...,0.375,1.0,1.0,1.0,5.0,5.0,1.0,124.0,133.0,NaN

In [8]:
int_cols = [
    "personId",
    "season",
    "gameId",
    "home",
    "win",
    "points",
    "assists",
    "reboundsDefensive",
    "reboundsOffensive",
    "reboundsTotal",
    "blocks",
    "steals",
    "turnovers",
    "foulsPersonal",
    "plusMinusPoints",
    "fieldGoalsAttempted",
    "fieldGoalsMade",
    "threePointersAttempted",
    "threePointersMade",
    "freeThrowsAttempted",
    "freeThrowsMade",
    "homeScore",
    "awayScore",
    "attendance"
]

for col in int_cols:
    player_games[col] = (
        player_games[col]
        .fillna(0)
        .astype("Int64")
    )

In [ ]:
def minutes_to_float(x):
    if pd.isna(x):
        return 0

    if isinstance(x, str) and ":" in x:
        mins, secs = x.split(":")
        return int(mins) + int(secs) / 60

    return float(x)

player_games["numMinutes"] = (
    player_games["numMinutes"] # for old data format
    .apply(minutes_to_float)
)

In [10]:
player_season_games = (
    player_games
    .groupby(["personId", "season"])
    .apply(
        lambda df: df.drop(
            columns=["personId", "season"]
        ).to_dict("records")
    )
    .reset_index(name="games")
)

player_season_games.head()

/var/folders/r2/nvsgtzs1435dg6fbzv1sn9b00000gn/T/ipykernel_2770/2789545174.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

   personId  season                                              games
0         0       0  [{'gameId': 10700002, 'gameDateTimeEst': NaT, ...
1         2    1983  [{'gameId': 28300002, 'gameDateTimeEst': 1983-...
2         2    1984  [{'gameId': 28400007, 'gameDateTimeEst': 1984-...
3         2    1985  [{'gameId': 28500019, 'gameDateTimeEst': 1985-...
4         2    1986  [{'gameId': 28600018, 'gameDateTimeEst': 1986-...

In [11]:
import os

output_dir = "../../src/data/games_by_player"
os.makedirs(output_dir, exist_ok=True)

for person_id, df in player_games.groupby("personId"):
    df = df.sort_values(["season", "gameDateTimeEst"])

    df.to_csv(
        f"{output_dir}/{person_id}.csv",
        index=False
    )